var userName = window.prompt('what is your name?')
var userAge = window.prompt('what is your age?')
var userColor = window.prompt('what is your favorite color?')
window.alert('Your name is ' + userName + '. ' + 'Your age is ' + userAge + '. ' + 'Your favorite color is ' + userColor + '.')
window.alert('Nice to meet you, ' + userName)
